### ISSUE TITLE
Doesn't support latest Firebase in iOS

### ISSUE THREAD

**Issue by WillBeebe** [sam0829/firebase_auth_ui#24]
This compiles
```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.0+2
```

This doesn't
```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.0+2
  firebase_auth_ui: 1.0.1
```

The error is:

```
In file included from
    /Users/will/repos/loveblocks-labs/flutter_android_ios/flutter_android_ios/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIR
    CDLibrary/FIRCoreDiagnostics.m:24:
    /Users/will/repos/loveblocks-labs/flutter_android_ios/flutter_android_ios/ios/Pods/FirebaseCoreDiagnostics/GoogleUtilities/Logger/Priva
    te/GULLogger.h:22:9: fatal error: 'GoogleUtilities/GULLoggerLevel.h' file not found
    #import <GoogleUtilities/GULLoggerLevel.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

The packages used in this [blog post](https://medium.com/flutterpub/firebase-ui-with-flutter-ccd6d4d6807) are too old. I'm now following a promising [guide](https://blog.codemagic.io/firebase-authentication-google-sign-in-using-flutter/) that has fewer, generic dependencies.

It looks like that will work but I love this Library so I'm hoping to come back to it someday and rip out the workaround code. Cheers mate!
